CREATE DATABASE treinamento;

DROP TABLE IF EXISTS STATE CASCADE;

CREATE TABLE OPERADORA (
ID BIGSERIAL NOT NULL PRIMARY KEY, 
NOME varchar(100) NOT NULL,
CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE CONTATO (
ID BIGSERIAL NOT NULL PRIMARY KEY, 
NAME varchar(100) NOT NULL,
TELEFONE bigint NOT NULL,
ID_OPERADORA bigint NOT NULL,
CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);


INSERT INTO operadora values(14, 'Oi');
INSERT INTO operadora values(15, 'Vivo');
INSERT INTO operadora values(41, 'Tim');
INSERT INTO operadora values(25, 'GVT');
INSERT INTO operadora values(21, 'Embratel');

INSERT INTO CONTATO(NAME,TELEFONE,ID_OPERADORA) VALUES('JOAO', 989698966, 14);
INSERT INTO CONTATO(NAME,TELEFONE,ID_OPERADORA) VALUES('Maria', 989698965, 41);
INSERT INTO CONTATO(NAME,TELEFONE,ID_OPERADORA) VALUES('Priscila', 989698964, 21);